name: Actions Workflow
on:
  pull_request:
    # branches-ignore:  # exexute on all branches except develop
    #   - develop 
    branches:
      - develop
      - 'feature/*' # matches feature/abc but not feature/abc/def
      - 'feature/**' # matches feature/abc and also feature/abc/def
      - '!feature/abc' # excludes feature/abc even after matches
    tags:
      - v1.*
    paths:
      - '**.js'
    # paths-ignore:
    #   - 'docs/**'
  # pull_request:
  # repository_dispatch:
  #   types: [build]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: check payload
        run: echo "${{  github.event.client_payload.env }}"
      # - name: List files
      #   run: |
      #     pwd
      #     ls -a
      #     echo "commit id :" $GITHUB_SHA
      #     echo "github repository :" $GITHUB_REPOSITORY
      #     echo "github workspace :" $GITHUB_WORKSPACE
      # - name: Checkout 
      #   uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls -a
      - name: Simple JS actions
        id: greet  
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Suraj
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }} seconds"
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail