name: Matrix
on: push
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [12, 14, 18]
      # max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - name: log node version 
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ strategy.matrix.node_version }}
      - name: log node version
        run: node -v